name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
    - name: Deploy
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: 15.237.46.184
        username: root
        key: ${{secrets.SSH_PRIVATE_KEY}}
        port: 22
        script: |
          cd /var/www/HotelMiranda-laravel
          git pull
          composer install --no-dev
          php artisan migrate
          systemctl restart apache2