name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
    - name: Deploy
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: 172-31-10-206
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/HotelMiranda-laravel
          git pull
          composer install --no-dev
          php artisan migrate
          systemctl restart apache2